$meses = ['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
$epoca = ['Águas','Águas','Águas','Águas','Seca','Seca','Seca','Seca','Seca','Águas','Águas','Águas'];

$peso = {
'1':['janeiro','1','31',0.59,0.64,0.69],
'2':['fevereiro','2','28',0.59,0.64,0.69],
'3':['março','3','31',0.49,0.54,0.59],
'4':['abril','4','30',0.49,0.54,0.59],
'5':['maio','5','31',0.14,0.19,0.24],
'6':['junho','6','30',0.14,0.19,0.24],
'7':['julho','7','31',0.09,0.14,0.19],
'8':['agosto','8','31',0.04,0.09,0.14],
'9':['setembro','9','30',0,0,0],
'10':['outubro','10','31',0,0,0],
'11':['novembro','11','30',0.29,0.34,0.39],
'12':['dezembro','12','31',0.49,0.54,0.59]
};

$estrategia = {
'311':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'321':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'331':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'341':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'351':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'361':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'371':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'381':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'391':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'3101':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'3111':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'3121':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'312':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'322':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'332':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'342':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'352':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'362':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'372':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'382':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'392':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'3102':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'3112':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'3122':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'313':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'323':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'333':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'343':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'353':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'363':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'373':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'383':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'393':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'3103':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'3113':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'3123':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'314':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'324':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'334':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'344':['Pró-Engorda','Pró-EngordAa','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'354':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'364':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'374':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'384':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'394':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'3104':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'3114':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'3124':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'411':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'421':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'431':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'441':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'451':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'461':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'471':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'481':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'491':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'4101':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'4111':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'4121':['Linea 60','Linea 60','Linea 60','Linea 60','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 60','Linea 60','Linea 60'],
'412':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'422':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'432':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'442':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'452':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'462':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'472':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'482':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'492':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'4102':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'4112':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'4122':['Engorda MD','Engorda MD','Engorda MD','Engorda MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Engorda MD','Engorda MD','Engorda MD'],
'413':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'423':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'433':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'443':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'453':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'463':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'473':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'483':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'493':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'4103':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'4113':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'4123':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'414':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'424':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'434':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'444':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'454':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'464':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'474':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'484':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'494':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'4104':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'4114':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'4124':['Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda','Pró-Engorda'],
'511':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'521':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'531':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'541':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'551':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'561':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'571':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'581':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'591':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'5101':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'5111':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'5121':['Linea 40','Linea 40','Linea 40','Linea 40','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Ureia 20','Linea 40','Linea 40','Linea 40'],
'512':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'522':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'532':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'542':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'552':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'562':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'572':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'582':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'592':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'5102':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'5112':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'5122':['Terminação MD','Terminação MD','Terminação MD','Terminação MD','MD Seca','MD Seca','MD Seca','MD Seca','MD Seca','Terminação MD','Terminação MD','Terminação MD'],
'513':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'523':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'533':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'543':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'553':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'563':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'573':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'583':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'593':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'5103':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'5113':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'5123':['Proteico Águas','Proteico Águas','Proteico Águas','Proteico Águas','Minerseca','Minerseca','Minerseca','Minerseca','Minerseca','Proteico Águas','Proteico Águas','Proteico Águas'],
'514':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'524':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'534':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'544':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'554':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'564':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'574':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'584':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'594':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'5104':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'5114':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas'],
'5124':['Pró-Águas','Pró-Águas','Pró-Águas','Pró-Águas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Secas','Pró-Águas','Pró-Águas','Pró-Águas']
};

$produtos = {
//Produto | Ganho Adicional | Consumo % PV | %MS | Efeito | Cálcio (%] | Fósforo (%] | Proteína Bruta (%] | Energia (NDT - %] | R$ Saco
'Linea 40':[0.01,0.022,97,100,19,4,0,0,44.01],
'Linea 60':[0.01,0.022,97,100,18,6,0,0,51.16],
'Engorda MD':[0.1,0.030,95,100,9,4,2,19.5,56.29],
'Terminação MD':[0.1,0.030,95,100,9.5,2.8,2,19.5,51.89],
'Proteico Águas':[0.19,0.100,90,120,2.5,1.5,30,45,52.40],
'Pró-Engorda':[0.36,0.300,95,100,1.5,0.7,30,67,53.82],
'MD Seca':[0.1,0.060,90,120,8,2.8,42.2,19.5,48.68],
'Minerseca':[0.21,0.100,95,120,2,1.1,40,40,50.27],
'Pró-Águas':[0.51,0.500,95,85,1,0.4,20,62,48.34],
'Ureia 20':[0,0.030,97,105,5,4,56.2,0,53.20],
'Pró-Secas':[0.76,1,90,65,1,0.4,20,64,46.84]
};


$porcents = {
//'Meses do Ano','IMS','Cálcio (g]','Fósforo (g]','Proteína Bruta (g]','Energia (NDT - g]'],
'5':[2,0.20,0.14,14,60],
'6':[2,0.20,0.14,13,55],
'7':[1.8,0.20,0.14,13,55],
'8':[1.8,0.20,0.12,12,55],
'9':[1.8,0.20,0.10,10,50],
'10':[2,0.30,0.12,12,55],
'11':[2,0.30,0.16,14,60],
'12':[2.2,0.30,0.16,16,60],
'1':[2.2,0.25,0.16,16,60],
'2':[2.2,0.25,0.16,14,60],
'3':[2.2,0.25,0.16,14,55],
'4':[2,0.25,0.16,14,55]
};
